config/routes.rb
Rails.application.routes.draw do
  get 'reports/index'
  post '/users', to: 'users#create', as: :users_create_path
  patch '/users', to: 'users#update', as: :users_update_path

  devise_for :users, controllers: {
      sessions: 'users/sessions',
      passwords: 'users/passwords',
      registrations: 'users/registrations',
      invitations: 'users/invitations'
  }

  resources :chapters
  resources :users

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  authenticated :user, ->(u) { u.role == 'external' } do
    root to: "forms#index", as: :external_root
  end

  authenticated :user, ->(u) { u.role == 'admin' } do
    root to: "admins#index", as: :admins_root
  end

  authenticated :user, ->(u) { u.role == 'reviewer' } do
    root to: "reports#index", as: :reviewer_root
  end

  root to: "home#index"

  get '/forms/index' => 'forms#index'
  get '/forms/training', to: 'trainings#new', as: 'trainings'
  post '/forms/training', to: 'trainings#create'
  get '/forms/street', to: 'street_swarms#new', as: 'street_swarms'
  post '/forms/street', to: 'street_swarms#create'
  get '/forms/actions', to: 'arrestable_actions#new', as: 'arrestable_actions'
  post '/forms/actions', to: 'arrestable_actions#create'
  get '/forms/growth_activity', to: 'growth_activities#new', as: 'growth_activities'
  post '/forms/growth_activity', to: 'growth_activities#create'
  get '/forms/blitzing', to: 'social_media_blitzings#new', as: 'social_media_blitzings'
  post '/forms/blitzing', to: 'social_media_blitzings#create'

  get 'admins/index' => 'admins#index'

  get 'new_user' => 'users#new'

  get '/reports', to: 'reports#index', as: 'reports'
  get '/reports/tiles', to: 'reports#tiles', as: 'report_tiles'
  get '/reports/table', to: 'reports#table', as: 'report_table'
  get '/reports/charts/mobilizations', to: 'reports#mobilizations', as: 'report_charts_mobilizations'
  get '/reports/:country', to: 'reports#index'
  get '/reports/:country/:state', to: 'reports#index'

  get '/locations/states', to: 'locations#states'
  get '/locations/cities', to: 'locations#cities'

  get '/csvs/download', to: 'csvs#download', as: 'csv_download'

  post 'resend_user_invitation/:id', to: 'users#resend_user_invitation', as: 'resend_user_invitation'
end

app/models/training.rb
class Training < ApplicationRecord
  belongs_to :user
  belongs_to :chapter

  has_one :address, through: :chapter

  scope :with_addresses, -> { includes(:address) }

  def self.training_type_options
    ['Induction',
     'DNA',
     'H4E',
     'NVDA',
     'Facilitation',
     'How to start a new chapter',
     'Mass mobilization',
     'Oppression & Movement Building']
  end

  validates :user, :chapter, presence: true
  validates :number_attendees,
            numericality: { only_integer: true,
                            :greater_than_or_equal_to => 1,
                            less_than_or_equal_to: 1_000_000_000 }
  validates :training_type, presence: true, :inclusion => { message: "must be a valid training type", in: Training.training_type_options }
  validates_length_of :identifier, maximum: 50

  def self.to_csv
    attributes = %w{chapter_name coordinator_email number_attendees training_type identifier report_date created_at}

    CSV.generate(headers: true) do |csv|
      csv << attributes

      all.includes(:chapter, :user).find_each do |m|
        csv << [m.chapter.name, m.user.email, m.number_attendees, m.training_type, m.identifier, m.report_date, m.created_at]
      end
    end
  end
end

app/controllers/trainings_controller.rb
class TrainingsController < ApplicationController
  protect_from_forgery with: :exception

  before_action :authenticate_user!

  def new
    @types = Training.training_type_options
    @training = Training.new
    authorize! :new, TrainingsController
  end

  def create
    date_params = params[:report_date]
    localTime = DateTime.parse(date_params)
    report_date = localTime.beginning_of_week
    @training = Training.new(
      number_attendees: params[:training][:number_attendees],
      training_type: params[:training_type],
      chapter: current_user.chapter,
      user: current_user,
      identifier: params[:training][:identifier],
      report_date: report_date
    )

    if @training.save
      flash[:success] = "#{@training.training_type} training was successfully registered!"
      redirect_to trainings_path
    else
      flash.now[:errors] = @training.errors.messages.values.flatten
      @types = Training.training_type_options
      render "new"
    end
  end
end

app/views/trainings/_form.html.erb
<div class="container-fluid">
  <div class="nav col-md-12 action-form">
    <div class="nav flex-column nav-pills col-md-5 col-lg-4 col-xl-3" id="v-pills-tab" role="tablist" aria-orientation="vertical">
      <% @types.each do |type| %>
        <a class="nav-link action-btn-active" id="v-pills-home-tab" data-toggle="pill"
          href="#v-pills-home" role="tab" aria-controls="v-pills-home" aria-selected="false"><%= type %></a>
      <% end %>
    </div>
    <div class="tab-content col-md-6 action-form-content">
      <div class="tab-pane fade show active" id="tab-container" role="tabpanel" aria-labelledby="v-pills-home-tab">
        <div class="report-form-body" id="hide-when-type-selected">
          <div class="default-tab-text">Form will appear here</div>
        </div>
        <div class="report-form-body" id="hide-until-type-selected">
          <%= form_for @training do |f| %>
            <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
            <%= hidden_field_tag :training_type, "", id: "training-type-input" %>
            <div class="form-group">
              <div>
                <%= f.label :number_attendees, "# of Attendees", class: "action-form-label" %>
                <%= f.text_field :number_attendees, class: "form-control action-form-input"%>
              </div>
            </div>
            <div class="form-group">
              <div>
                <%= f.submit "Submit Section", class: "btn action-submit-btn"%>
              </div>
              <p class="warning">Cannot undo this action</p>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>
<script>
(() => {
  const navLinks = document.getElementsByClassName('nav-link');

  for(const navLink of navLinks) {
    navLink.addEventListener('click', e => {
      document.getElementById('training-type-input').value = e.target.textContent;

      for(const navLinkToModify of navLinks) {
        navLinkToModify.classList.remove('active');
        navLink.setAttribute('aria-selected', false);
      }

      navLink.classList.add('active');
      navLink.setAttribute('aria-selected', true);

      document.getElementById('hide-until-type-selected').style.display = 'block';
      document.getElementById('tab-container').style.display = 'block';
      document.getElementById('hide-when-type-selected').style.display = 'none';
    });
  }
  
})();
</script>

app/views/trainings/_form_body.html.erb
<%= form_for @training do |f| %>
  <h2 id="form-title">&nbsp;</h2>
  <%= hidden_field_tag :training_type, "", id: "training-type-input" %>
  <%= hidden_field_tag :report_date %>
  <div class="form-group">
    <div>
      <%= f.label :number_attendees, "Number of Attendees*", class: "action-form-label" %>
      <%= f.text_field :number_attendees, class: "form-control action-form-input clearable", placeholder: 'Enter Number'%>
    </div>
  </div>
  <div class="form-group">
    <div>
      <%= f.label :identifier, "Identifier (max 50 characters)", class: "action-form-label" %>
      <%= f.text_field :identifier, class: "form-control clearable", placeholder: 'Enter Identifier', :maxlength => 50%>
    </div>
  </div>
  <div class="form-group">
    <div>
      <%= link_to 'Cancel', trainings_path, class: "btn cancel-button"%>
      <%= f.submit "Submit Section", class: "btn submit-button"%>
    </div>
    <p class="warning">Cannot undo this action</p>
  </div>
<% end %>
<script>
    var localTime = new Date();
    $('#report_date').val(localTime)
</script>

app/views/trainings/new.html.erb
<div class="container-fluid">
  <div class="content">
    <div class="text-left col-md-8 show-on-mobile" style="margin-bottom: 20px">
      <%= link_to forms_index_path, :action => 'go', :class => "test-cancel-street-swarm" do %>
        < Back to Report Entry Menu
      <% end %>
    </div>
    <%= render 'layouts/messages', flash: flash %>
    <%= render 'forms/form_header', title: 'Trainings',
               subtitle: 'Click on tabs below to complete a form <strong>for each instance</strong> of a ‘Training’ your chapter completed this week.'.html_safe %>
    <%= render "forms/form", training: @training do |f| %>
      <%= render 'trainings/form_body' %>
    <% end %>
    <%= render "forms/form_footer", title: "Training" %>
  </div>
</div>