config/routes.rb
Rails.application.routes.draw do
  get 'reports/index'
  post '/users', to: 'users#create', as: :users_create_path
  patch '/users', to: 'users#update', as: :users_update_path

  devise_for :users, controllers: {
      sessions: 'users/sessions',
      passwords: 'users/passwords',
      registrations: 'users/registrations',
      invitations: 'users/invitations'
  }

  resources :chapters
  resources :users

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  authenticated :user, ->(u) { u.role == 'external' } do
    root to: "forms#index", as: :external_root
  end

  authenticated :user, ->(u) { u.role == 'admin' } do
    root to: "admins#index", as: :admins_root
  end

  authenticated :user, ->(u) { u.role == 'reviewer' } do
    root to: "reports#index", as: :reviewer_root
  end

  root to: "home#index"

  get '/forms/index' => 'forms#index'
  get '/forms/training', to: 'trainings#new', as: 'trainings'
  post '/forms/training', to: 'trainings#create'
  get '/forms/street', to: 'street_swarms#new', as: 'street_swarms'
  post '/forms/street', to: 'street_swarms#create'
  get '/forms/actions', to: 'arrestable_actions#new', as: 'arrestable_actions'
  post '/forms/actions', to: 'arrestable_actions#create'
  get '/forms/growth_activity', to: 'growth_activities#new', as: 'growth_activities'
  post '/forms/growth_activity', to: 'growth_activities#create'
  get '/forms/blitzing', to: 'social_media_blitzings#new', as: 'social_media_blitzings'
  post '/forms/blitzing', to: 'social_media_blitzings#create'

  get 'admins/index' => 'admins#index'

  get 'new_user' => 'users#new'

  get '/reports', to: 'reports#index', as: 'reports'
  get '/reports/tiles', to: 'reports#tiles', as: 'report_tiles'
  get '/reports/table', to: 'reports#table', as: 'report_table'
  get '/reports/charts/mobilizations', to: 'reports#mobilizations', as: 'report_charts_mobilizations'
  get '/reports/:country', to: 'reports#index'
  get '/reports/:country/:state', to: 'reports#index'

  get '/locations/states', to: 'locations#states'
  get '/locations/cities', to: 'locations#cities'

  get '/csvs/download', to: 'csvs#download', as: 'csv_download'

  post 'resend_user_invitation/:id', to: 'users#resend_user_invitation', as: 'resend_user_invitation'
end

app/views/admins/index.html.erb
<div class="content">
  <%= render 'layouts/messages', flash: flash %>
  <div class="admin-page container">
    <%= render 'layouts/page_header',
               title: 'Hello, Admin',
               subtitle: 'This is where you help build the ‘Metrics for Mobilizers’ database and manage permissions. You must onboard a chapter before you can assign a User to it.',
               disclaimer: '*Each chapter has a limit of 2 Coordinators.'%>
    <div class="row">
      <div class="col-lg-2 col-md-12 col-sm-12 col-xs-12 outer-box">
        <div class="left-nav full-height">
          <h5 class="nav-title">Onboarding</h5>
          <a class="left-nav-item selected" id="users-nav-link">
            <div class="left-nav-icon extra-padding"><span class="fa fa-user"></span></div>
            <div class="left-nav-text">User</div>
          </a>
          <a class="left-nav-item" id="chapters-nav-link">
            <div class="left-nav-icon"><span class="fa fa-users"></span></div>
            <div class="left-nav-text">Chapter</div>
          </a>
        </div>
      </div>
      <div class="col-lg-10 col-md-12 col-sm-12 col-xs-12 outer-box">
        <div class="admin-page-content">
          <div class="content-top-row">
            <a id="link-chapters" href="<%= new_chapter_path %>">
              Add Chapter <span class="fa fa-plus-circle"></span>
            </a>
            <a id="link-users" href="<%= new_user_path %>">
              <span>Add User</span>
              <span class="fa fa-plus-circle"></span>
            </a>
          </div>
          <div class="container">
            <div id="content-chapters">
              <div class="content-header row">
                <div class="column col-4">Name</div>
                <div class="column col-2">Country</div>
                <div class="column col-2">State</div>
                <div class="column col-1 text-right">ZIP</div>
                <div class="column col-2 text-center">Created</div>
                <div class="column col-1"></div>
              </div>
              <div class="content-row-container">
                <% @chapters.each do |chapter| %>
                  <div class="content-row row">
                    <div class="column col-4"><%= chapter.name %></div>
                    <div class="column col-2"><%= !chapter.address.nil? ? chapter.address.country : "N/A" %></div>
                    <div class="column col-2"><%= !chapter.address.nil? ? chapter.address.state_province : "N/A" %></div>
                    <div class="column col-1 text-right"><%= !chapter.address.nil? ? chapter.address.zip_code : "N/A" %></div>
                    <div class="column col-2 text-center"><%= chapter.created_at.strftime("%m/%d/%Y") %></div>
                    <div class="column col-1"><%= link_to '', edit_chapter_path(chapter.id), class: "fa fa-pencil", title: 'Edit Chapter' %></div>
                  </div>
                <% end %>
                <% if @chapters.empty? %>
                <div class="row align-items-center justify-content-center">
                  <div class="col empty-chapters ">
                    No chapters registered in the application
                  </div>
                </div>
                <% end %>
              </div>
            </div>

            <div id="content-users">
              <div class="content-header row">
                <div class="column col-4">Name</div>
                <div class="column col-3">Chapter</div>
                <div class="column col-2">Role</div>
                <div class="column col-2">Created</div>
                <div class="column col-1"></div>
              </div>

              <div class="content-row-container">
                <% @users.each do |user| %>
                  <div class="content-row row">
                    <div class="column col-4"><%= user.invitation_token.nil? ? user.first_name : user.email %> <%= user.invitation_token.nil? ? user.last_name : "" %></div>
                    <div class="column col-3"><%= user.chapter.nil? ? "N/A" : user.chapter.name  %></div>
                    <% if user.external_coordinator? %>
                      <div class="column col-2">Coordinator</div>
                    <% else %>
                      <div class="column col-2"><%= user.role.capitalize %></div>
                    <% end %>
                    <div class="column col-2"><%= user.created_at.strftime("%m/%d/%Y") %></div>
                    <% if user.invitation_token.nil? %>
                      <div class="column col-1"><%= link_to '', edit_user_path(user.id), class: "fa fa-pencil", title: 'Edit User' %></div>
                    <% else %>
                      <div class="column col-1"><%= link_to '', resend_user_invitation_path(user.id), method: :post, class: "fa fa-envelope", id: "resend_user_email", title: 'Resend invite email' %></div>
                    <% end %>
                  </div>
                <% end %>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <%= image_tag('/images/half_circle.png', class: 'half-logo')%>
</div>