config/routes.rb
Rails.application.routes.draw do
  get 'reports/index'
  post '/users', to: 'users#create', as: :users_create_path
  patch '/users', to: 'users#update', as: :users_update_path

  devise_for :users, controllers: {
      sessions: 'users/sessions',
      passwords: 'users/passwords',
      registrations: 'users/registrations',
      invitations: 'users/invitations'
  }

  resources :chapters
  resources :users

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  authenticated :user, ->(u) { u.role == 'external' } do
    root to: "forms#index", as: :external_root
  end

  authenticated :user, ->(u) { u.role == 'admin' } do
    root to: "admins#index", as: :admins_root
  end

  authenticated :user, ->(u) { u.role == 'reviewer' } do
    root to: "reports#index", as: :reviewer_root
  end

  root to: "home#index"

  get '/forms/index' => 'forms#index'
  get '/forms/training', to: 'trainings#new', as: 'trainings'
  post '/forms/training', to: 'trainings#create'
  get '/forms/street', to: 'street_swarms#new', as: 'street_swarms'
  post '/forms/street', to: 'street_swarms#create'
  get '/forms/actions', to: 'arrestable_actions#new', as: 'arrestable_actions'
  post '/forms/actions', to: 'arrestable_actions#create'
  get '/forms/growth_activity', to: 'growth_activities#new', as: 'growth_activities'
  post '/forms/growth_activity', to: 'growth_activities#create'
  get '/forms/blitzing', to: 'social_media_blitzings#new', as: 'social_media_blitzings'
  post '/forms/blitzing', to: 'social_media_blitzings#create'

  get 'admins/index' => 'admins#index'

  get 'new_user' => 'users#new'

  get '/reports', to: 'reports#index', as: 'reports'
  get '/reports/tiles', to: 'reports#tiles', as: 'report_tiles'
  get '/reports/table', to: 'reports#table', as: 'report_table'
  get '/reports/charts/mobilizations', to: 'reports#mobilizations', as: 'report_charts_mobilizations'
  get '/reports/:country', to: 'reports#index'
  get '/reports/:country/:state', to: 'reports#index'

  get '/locations/states', to: 'locations#states'
  get '/locations/cities', to: 'locations#cities'

  get '/csvs/download', to: 'csvs#download', as: 'csv_download'

  post 'resend_user_invitation/:id', to: 'users#resend_user_invitation', as: 'resend_user_invitation'
end

app/controllers/form_controller.rb
class FormController < ApplicationController
  protect_from_forgery with: :exception

  before_action :authenticate_user!
end

app/controllers/forms_controller.rb
class FormsController < ApplicationController
  before_action :authenticate_user!

  def index
    authorize! :index, FormsController
    @chapter = current_user.chapter
  end
end

app/views/form/index.html.erb
<div class="container-fluid default-background">
  <div class="row">
    <div class="col-10 offset-1 col-sm-8 offset-sm-3 col-md-8 offset-md-2 col-lg-5 offset-lg-2 form-title">
      Click to complete for each activity category
      your chapter participated in this week.
    </div>
  </div>
  <div class="row form-row">
    <%= link_to form_mobilization_path, :action => 'go', :class => "col-9 col-sm-4 col-md-3 form-tile" do %>
        <p class="tile-title">Mobilizations</p>
        <p class="tile-desc">All activities that are recruiting driven</p>
    <% end %>
    <%= link_to form_training_path, :action => 'go', :class => "col-9 col-sm-4 col-md-3 form-tile" do %>
      <p class="tile-title">Trainings</p>
      <p class="tile-desc">All activities conducted for XRA members</p>
    <% end %>
  </div>
  <div class="row">
    <%= link_to form_street_path, :action => 'go', :class => "col-9 col-sm-4 col-md-3 form-tile" do %>
      <p class="tile-title">Street Swarms</p>
      <p class="tile-desc">Insert definition of this activity here</p>
    <% end %>
    <%= link_to form_arrestable_path, :action => 'go', :class => "col-9 col-sm-4 col-md-3 form-tile" do %>
      <p class="tile-title">Arrestable Actions</p>
      <p class="tile-desc">Insert definition of this activity here</p>
    <% end %>
  </div>
  <%= image_tag('/images/half_circle.png', class: 'half-logo')%>
</div>