config/routes.rb
Rails.application.routes.draw do
  get 'reports/index'
  post '/users', to: 'users#create', as: :users_create_path
  patch '/users', to: 'users#update', as: :users_update_path

  devise_for :users, controllers: {
      sessions: 'users/sessions',
      passwords: 'users/passwords',
      registrations: 'users/registrations',
      invitations: 'users/invitations'
  }

  resources :chapters
  resources :users

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  authenticated :user, ->(u) { u.role == 'external' } do
    root to: "forms#index", as: :external_root
  end

  authenticated :user, ->(u) { u.role == 'admin' } do
    root to: "admins#index", as: :admins_root
  end

  authenticated :user, ->(u) { u.role == 'reviewer' } do
    root to: "reports#index", as: :reviewer_root
  end

  root to: "home#index"

  get '/forms/index' => 'forms#index'
  get '/forms/training', to: 'trainings#new', as: 'trainings'
  post '/forms/training', to: 'trainings#create'
  get '/forms/street', to: 'street_swarms#new', as: 'street_swarms'
  post '/forms/street', to: 'street_swarms#create'
  get '/forms/actions', to: 'arrestable_actions#new', as: 'arrestable_actions'
  post '/forms/actions', to: 'arrestable_actions#create'
  get '/forms/growth_activity', to: 'growth_activities#new', as: 'growth_activities'
  post '/forms/growth_activity', to: 'growth_activities#create'
  get '/forms/blitzing', to: 'social_media_blitzings#new', as: 'social_media_blitzings'
  post '/forms/blitzing', to: 'social_media_blitzings#create'

  get 'admins/index' => 'admins#index'

  get 'new_user' => 'users#new'

  get '/reports', to: 'reports#index', as: 'reports'
  get '/reports/tiles', to: 'reports#tiles', as: 'report_tiles'
  get '/reports/table', to: 'reports#table', as: 'report_table'
  get '/reports/charts/mobilizations', to: 'reports#mobilizations', as: 'report_charts_mobilizations'
  get '/reports/:country', to: 'reports#index'
  get '/reports/:country/:state', to: 'reports#index'

  get '/locations/states', to: 'locations#states'
  get '/locations/cities', to: 'locations#cities'

  get '/csvs/download', to: 'csvs#download', as: 'csv_download'

  post 'resend_user_invitation/:id', to: 'users#resend_user_invitation', as: 'resend_user_invitation'
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  include Regions

  DATE_RANGE_MAPPING = {
      :week => 6,
      :month => 29,
      :quarter => 89,
      :'half-year' => 179
  }

  def index
    if params[:chapter]
      @chapter_name = Chapter.find(params[:chapter]).name
    end
  end

  def tiles
    country = params[:country]
    state = params[:state]
    region = params[:region]
    chapter_id = params[:chapter]
    date_range_days = DATE_RANGE_MAPPING[params[:dateRange].to_sym]

    if country.nil?
      chapter_data = Chapter.all.pluck(:id, :total_mobilizers, :total_subscription_amount, :total_arrestable_pledges)
      chapter_data_this_period = Chapter.
          where('chapters.created_at BETWEEN ? AND ?' , (DateTime.now - date_range_days.days).beginning_of_day, DateTime.now.end_of_day).
          pluck(:id, :total_mobilizers, :total_subscription_amount, :total_arrestable_pledges)


    elsif country.upcase == 'US' && !region.nil? && state.nil?
      states = Regions.us_regions[region.to_sym][:states]
      chapter_data = Chapter.with_addresses.where(addresses: {country: 'United States', state_province: states}).
          pluck(:id, :total_mobilizers, :total_subscription_amount, :total_arrestable_pledges)

      chapter_data_this_period = Chapter.with_addresses.
          where(addresses: {country: 'United States', state_province: states}).
          where('chapters.created_at BETWEEN ? AND ?' , (DateTime.now - date_range_days.days).beginning_of_day, DateTime.now.end_of_day).
          pluck(:id, :total_mobilizers, :total_subscription_amount, :total_arrestable_pledges)


    elsif state.nil?
      country = CS.countries[country.to_sym]
      chapter_data = Chapter.with_addresses.where(addresses: {country: country}).
          pluck(:id, :total_mobilizers, :total_subscription_amount, :total_arrestable_pledges)

      chapter_data_this_period = Chapter.with_addresses.where(addresses: {country: country}).
          where('chapters.created_at BETWEEN ? AND ?' , (DateTime.now - date_range_days.days).beginning_of_day, DateTime.now.end_of_day).
          pluck(:id, :total_mobilizers, :total_subscription_amount, :total_arrestable_pledges)


    elsif chapter_id.nil?
      state = validate_state(country, state)
      country = CS.countries[country.to_sym]
      chapter_data = Chapter.with_addresses.where(addresses: {state_province: state, country: country}).
          pluck(:id, :total_mobilizers, :total_subscription_amount, :total_arrestable_pledges)

      chapter_data_this_period = Chapter.with_addresses.
          where(addresses: {state_province: state, country: country}).
          where('chapters.created_at BETWEEN ? AND ?' , (DateTime.now - date_range_days.days).beginning_of_day, DateTime.now.end_of_day).
          pluck(:id, :total_mobilizers, :total_subscription_amount, :total_arrestable_pledges)


    else
      chapter_data = Chapter.where(id: chapter_id).
          pluck(:id, :total_mobilizers, :total_subscription_amount, :total_arrestable_pledges, :total_arrestable_pledges)

      chapter_data_this_period = Chapter.with_addresses.where(id: chapter_id).
                             where('chapters.created_at BETWEEN ? AND ?' , (DateTime.now - date_range_days.days).beginning_of_day, DateTime.now.end_of_day).
                                     pluck(:id, :total_mobilizers, :total_subscription_amount, :total_arrestable_pledges)
    end

    mobilizations_this_period = GrowthActivity.where(chapter_id: chapter_data.map(&:first)).
        where('created_at BETWEEN ? AND ?' , (DateTime.now - date_range_days.days).beginning_of_day, DateTime.now.end_of_day).
        pluck(:newsletter_sign_ups, :arrestable_pledges, :new_mobilizer_sign_ons, :total_donation_subscriptions, :chapter_id)
    mobilizations_previous_period = GrowthActivity.where(chapter_id: chapter_data.map(&:first)).
        where('created_at BETWEEN ? AND ?' , (DateTime.now - calculate_days_ago_for_previous_period(date_range_days).days).beginning_of_day, (DateTime.now - date_range_days.days).beginning_of_day).
        pluck(:newsletter_sign_ups, :arrestable_pledges)

    trainings_this_period = Training.where(chapter_id: chapter_data.map(&:first)).
        where('created_at BETWEEN ? AND ?' , (DateTime.now - date_range_days.days).beginning_of_day, DateTime.now.end_of_day).
        pluck(:id)
    trainings_previous_period = Training.where(chapter_id: chapter_data.map(&:first)).
        where('created_at BETWEEN ? AND ?' , (DateTime.now - calculate_days_ago_for_previous_period(date_range_days).days).beginning_of_day, (DateTime.now - date_range_days.days).beginning_of_day).
        pluck(:id)

    street_swarms_this_period = StreetSwarm.where(chapter_id: chapter_data.map(&:first)).
        where('created_at BETWEEN ? AND ?' , (DateTime.now - date_range_days.days).beginning_of_day, DateTime.now.end_of_day).
        pluck(:id)
    street_swarms_previous_period = StreetSwarm.where(chapter_id: chapter_data.map(&:first)).
        where('created_at BETWEEN ? AND ?' , (DateTime.now - calculate_days_ago_for_previous_period(date_range_days).days).beginning_of_day, (DateTime.now - date_range_days.days).beginning_of_day).
        pluck(:id)

    arrestable_actions_this_period = ArrestableAction.where(chapter_id: chapter_data.map(&:first)).
        where('created_at BETWEEN ? AND ?' , (DateTime.now - date_range_days.days).beginning_of_day, DateTime.now.end_of_day).
        pluck(:id)
    arrestable_actions_previous_period = ArrestableAction.where(chapter_id: chapter_data.map(&:first)).
        where('created_at BETWEEN ? AND ?' , (DateTime.now - calculate_days_ago_for_previous_period(date_range_days).days).beginning_of_day, (DateTime.now - date_range_days.days).beginning_of_day).
        pluck(:id)

    report_data = {
        chapters: chapter_data.length,
        chapters_growth: chapter_data_this_period.count,
        members: sum_data(chapter_data, 1),
        members_growth: get_members_growth(chapter_data_this_period, mobilizations_this_period),
        subscriptions: sum_data(chapter_data, 2).to_int,
        subscriptions_growth: get_subscriptions_growth(chapter_data_this_period, mobilizations_this_period),
        arrestable_pledges: sum_data(chapter_data, 3),
        arrestable_pledges_growth: get_arrestable_pledges_growth(chapter_data_this_period, mobilizations_this_period),
        mobilizations: mobilizations_this_period.length,
        mobilizations_growth: mobilizations_this_period.length - mobilizations_previous_period.length,
        signups: sum_data(mobilizations_this_period, 0),
        signups_growth: sum_data(mobilizations_this_period, 0) - sum_data(mobilizations_previous_period, 0),
        trainings: trainings_this_period.length,
        trainings_growth: trainings_this_period.length - trainings_previous_period.length,
        actions: street_swarms_this_period.length + arrestable_actions_this_period.length,
        actions_growth: (street_swarms_this_period.length + arrestable_actions_this_period.length) - (street_swarms_previous_period.length + arrestable_actions_previous_period.length),
        start_date: (DateTime.now - date_range_days.days).strftime("%d %B %Y"),
        end_date: DateTime.now.strftime("%d %B %Y")
    }

    render json: report_data
  end

  def mobilizations
    render json: {
        labels: get_chart_labels_for_period(params[:dateRange]),
        data: get_chart_data(params[:dateRange],
                             params[:country],
                             params[:region],
                             params[:state],
                             params[:chapter]
        )
    }
  end

  def table
    country = params[:country]
    state = params[:state]
    region = params[:region]
    chapter = params[:chapter]
    date_range_days = DATE_RANGE_MAPPING[params[:period].to_sym]
    begin
      response = if country.nil?
                   all_countries(date_range_days)
                 elsif country.upcase == 'US' && region.nil?
                   us_regions(date_range_days)
                 elsif country.upcase == 'US' && !region.nil? && state.nil?
                   us_states(region, date_range_days)
                 elsif state.nil?
                   states(country, date_range_days)
                 elsif chapter.nil?
                   chapters(country, state, date_range_days)
                 else
                   chapter_report(chapter, date_range_days)
                 end
      render json: response
    rescue
      render json: {error: true}
    end
  end

  private

  def sum_data(data, position)
    sum = data.map{|e| e[position]}.reduce(:+)
    sum ? sum : 0
  end

  def get_members_growth(chapter_data_this_period, mobilizations_this_period)
    chapter_ids = chapter_data_this_period.map {|row| row[0]}
    mobilizations_growth = sum_data(mobilizations_this_period.select { |m| chapter_ids.exclude? m[4] }, 2)
    mobilizations_growth + sum_data(chapter_data_this_period, 1)
  end

  def get_arrestable_pledges_growth(chapter_data_this_period, mobilizations_this_period)
    chapter_ids = chapter_data_this_period.map {|row| row[0]}
    mobilizations_growth = sum_data(mobilizations_this_period.select { |m| chapter_ids.exclude? m[4] }, 1)
    mobilizations_growth + sum_data(chapter_data_this_period, 3)
  end

  def get_subscriptions_growth(chapter_data_this_period, mobilizations_this_period)
    chapter_ids = chapter_data_this_period.map {|row| row[0]}
    mobilizations_growth = sum_data(mobilizations_this_period.select { |m| chapter_ids.exclude? m[4] }, 3).to_int
    mobilizations_growth + sum_data(chapter_data_this_period, 2).to_int
  end

  def calculate_days_ago_for_previous_period(date_range_days)
    date_range_days * 2 + 1
  end

  def all_countries(date_range_days)
    addresses_with_chapters = Chapter.with_addresses.group_by { |c| c.address.country }

    mobilizations_this_period = GrowthActivity.with_addresses.

app/helpers/reports_helper.rb
module ReportsHelper
end

app/views/reports/_report_charts.html.erb
<div class="row chart-padding-wrapper">
  <div class="chart-container col-12">
    <div class="chart-content">
      <h2>Growth Activities</h2>
      <h3>
        <span class="report-page-start-date">30 February 2020</span>
        -
        <span class="report-page-end-date">32 February 2020</span>
      </h3>

      <nav>
        <div class="nav nav-tabs chart-tabs" role="tablist">
          <a class="chart-tab active" href="#chart-participants" data-toggle="tab" >Engagement / Sign Ons</a>
          <a class="chart-tab"  href="#chart-subscriptions" data-toggle="tab" >Monthly Donor Subscriptions</a>
          <a class="chart-tab" href="#chart-arrestable"  data-toggle="tab" >Arrestable Pledges</a>
        </div>
      </nav>

      <div class="tab-content">

        <div id="chart-participants" class="tab-pane active" role="tabpanel">
          <div class="chart-prompt">
            This chart shows the total number of people engaged (gray) and the number of new sign ons (color) for each activity.
          </div>
          <div class="mobilizations-chart" >
            <!-- Canvas chart will populate here -->
          </div>
          <div class="chart-metrics">
            <div class="mobilization-metrics-container"></div>
            <div class="description">Colors Represent Totals New Sign Ons Per Activity.</div>
          </div>
        </div>

        <div id="chart-subscriptions" class="tab-pane" role="tabpanel">
          <div class="chart-prompt">
            Total Monthly Donor Subscriptions by Growth Activity
          </div>
          <div class="mobilizations-chart-subscriptions" >
            <!-- Canvas chart will populate here -->
          </div>
          <div class="chart-metrics">
            <div class="mobilization-metrics-container-subscriptions"></div>
            <div class="description">Colors represent total new Monthly Donor Subscriptions per Activity.</div>
          </div>
        </div>

        <div id="chart-arrestable" class="tab-pane" role="tabpanel">
          <div class="chart-prompt">
            Total New Arrestable Pledges by Growth Activity
          </div>
          <div class="mobilizations-chart-arrestable-pledges" >
            <!-- Canvas chart will populate here -->
          </div>
          <div class="chart-metrics">
            <div class="mobilization-metrics-container-arrestable-pledges"></div>
            <div class="description">Colors represent total New Arrestable Pledges per Activity.</div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/reports/_report_filter.html.erb
<div class="row">
  <div class="col-12">
    <div class="csv-download">
      <% if current_user.role == 'admin' %>
        <%= link_to csv_download_path, target: "_blank", id: "csv-download", class: "btn btn-lg login-button" do %>
          CSV <span class="fa fa-arrow-down"></span>
        <% end %>
      <% end %>
    </div>
  </div>
</div>
<div class="report-filter-container" id="sticky-filter-container">
  <div class="row">
    <div id="report-page-breadcrumbs" class="hidden">
      <h5>
        <a href="/reports" id="report-breadcrumb-global">Global</a>
        <span id="report-breadcrumb-country-wrapper" class="hidden">
          <span class="fa fa-angle-right"></span>
          <span id="report-breadcrumb-country">Country</span>
        </span>
        <span id="report-breadcrumb-region-wrapper" class="hidden">
          <span class="fa fa-angle-right"></span>
          <span id="report-breadcrumb-region">Region</span>
        </span>
        <span id="report-breadcrumb-state-wrapper" class="hidden">
          <span class="fa fa-angle-right"></span>
          <span id="report-breadcrumb-state">State</span>
        </span>
        <span id="report-breadcrumb-chapter-wrapper" class="hidden">
          <span class="fa fa-angle-right"></span>
          <span id="report-breadcrumb-chapter">Chapter</span>
        </span>
      </h5>
    </div>
    <div class="report-page-header-right">
      <div>Last <span class="filter-day-count">0</span> days</div>
      <nav class="nav nav-pills nav-justified">
        <a id="filter-week" class="nav-link">1W</a>
        <a id="filter-month" class="nav-link">1M</a>
        <a id="filter-quarter" class="nav-link">3M</a>
        <a id="filter-half-year" class="nav-link">6M</a>
      </nav>
    </div>
  </div>
</div>
<div class="row report-filter-container">
  <div class="report-page-header">
    <h2 id="report-page-title">Global</h2>
    <h2 class="report-page-subtitle">
      <span class="report-page-start-date">30 February 2020</span>
      -
      <span class="report-page-end-date">32 February 2020</span>
    </h2>
  </div>
</div>

<script>
  function initializeBreadcrumbs() {
      const countryNamesMapping = <%= CS.countries.to_json.html_safe %>;
      const regionNamesMapping = <%= Regions.us_regions.to_json.html_safe %>;

      let params = new URL(window.location.href).searchParams;
      let country = params.get('country');
      let state = params.get('state');
      let region = params.get('region');
      let chapter = params.get('chapter');

      if (!country) return;

      if (country) {
          $('#report-page-breadcrumbs').removeClass('hidden');
          showBreadCrumb('country', countryNamesMapping[country]);
          updateReportPageTitle(countryNamesMapping[country]);
      }

      if (region) {
          showBreadCrumb('region', regionNamesMapping[`${region}`]['name']);
          showBreadCrumb('country', `<a href="/reports?country=${country}">${countryNamesMapping[country]}</a>`);
          updateReportPageTitle(regionNamesMapping[`${region}`]['name']);
      }

      if (state && region) {
          showBreadCrumb('region', `<a href="/reports?country=${country}&region=${region}">${regionNamesMapping[`${region}`]['name']}</a>`);
      }

      if (state) {
          showBreadCrumb('state', state);
          updateReportPageTitle(state);
          showBreadCrumb('country', `<a href="/reports?country=${country}">${countryNamesMapping[country]}</a>`);
      }

      if (chapter) {
          showBreadCrumb('chapter', <%= @chapter_name.to_json.html_safe %>);
          updateReportPageTitle(<%= @chapter_name.to_json.html_safe %>);
      }

      if (chapter && region) {
          $('#report-breadcrumb-state').html(`<a href="/reports?country=${country}&region=${region}&state=${encodeURIComponent(state)}">${state}</a>`);
      }

      if (chapter && !region) {
          $('#report-breadcrumb-state').html(`<a href="/reports?country=${country}&state=${encodeURIComponent(state)}">${state}</a>`);
      }
  }

  function showBreadCrumb(type, htmlString) {
      $(`#report-breadcrumb-${type}-wrapper`).removeClass('hidden');
      $(`#report-breadcrumb-${type}`).html(htmlString);
  }

  function updateReportPageTitle(title) {
      $('#report-page-title').html(title);
  }

  initializeBreadcrumbs();

</script>

app/views/reports/_report_table.html.erb
<h5 class="reports-title">
  Navigate the reports by location in the table below.
</h5>
<div class="report-table-padding-wrapper">
  <div class="table-responsive report-table-container">
    <table class="table report-table">
      <thead>
      <tr>
        <td rowspan="1" class="report-table-title"></td>
        <td colspan="4" scope="colgroup" class="report-table-title">Totals All Time</td>
        <td colspan="4" scope="colgroup" class="report-table-title">Totals Last <span class="filter-day-count">7</span> Days</td>
      </tr>
      <tr>
        <th scope="col" xr-table-key=""></th>
        <th scope="col" xr-table-key="chapters">Chapters<i class="fa fa-sort"></i></th>
        <th scope="col" xr-table-key="members">Mobilizers<i class="fa fa-sort"></i></th>
        <th scope="col" xr-table-key="subscriptions">$ Subscriptions<i class="fa fa-sort"></i></th>
        <th scope="col" xr-table-key="arrestable_pledges">Pledges<i class="fa fa-sort"></i></th>
        <th scope="col" xr-table-key="mobilizations">Growth Activities<i class="fa fa-sort"></i></th>
        <th scope="col" xr-table-key="trainings">Trainings<i class="fa fa-sort"></i></th>
        <th scope="col" xr-table-key="signups">Newsletter signups<i class="fa fa-sort"></i></th>
        <th scope="col" xr-table-key="actions">Actions<i class="fa fa-sort"></i></th>
      </tr>
      </thead>
      <tbody>
      </tbody>
    </table>
  </div>
</div>

app/views/reports/_report_tiles.html.erb
<div class="report-tiles-container">
  <h5 class="reports-title">Totals All Time</h5>
  <div class="row">
    <div class="report-card-container col-xl-3 col-lg-6 col-md-6 col-sm-12">
      <div class="report-card-content">
        <div class="report-card-top">
          <div class="row">
            <div class="col-5">
              <h1 id="chapters">0</h1>
            </div>
            <div class="col-7 card-top-right">
              <h3>Total Chapters</h3>
            </div>
          </div>
        </div>
        <h4 class="report-card-title">Chapters</h4>
        <div class="report-card-bottom">
          <div class="row">
            <div class="col-5">
              <h5>
                <span class="growth-number" id="chapters-growth">0</span>
                <span class="fa fa-arrow-up"></span>
              </h5>
            </div>
            <div class="col-7">
              <h5>
                <span class="growth-description">New Chapters</span>
              </h5>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="report-card-container col-xl-3 col-lg-6 col-md-6 col-sm-12">
      <div class="report-card-content">
        <div class="report-card-top">
          <div class="row">
            <div class="col-5">
              <h1 id="members">0</h1>
            </div>
            <div class="col-7 card-top-right">
              <h3>Total Mobilizers</h3>
            </div>
          </div>
        </div>
        <h4 class="report-card-title">Mobilizers</h4>
        <div class="report-card-bottom">
          <div class="row">
            <div class="col-5">
              <h5>
                <span class="growth-number" id="members-growth">0</span>
                <span class="fa fa-arrow-up"></span>
              </h5>
            </div>
            <div class="col-7">
              <h5>
                <span class="growth-description">New Mobilizers</span>
              </h5>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="report-card-container col-xl-3 col-lg-6 col-md-6 col-sm-12">
      <div class="report-card-content">
        <div class="report-card-top">
          <div class="row">
            <div class="col-5">
              <h1>$<span id="subscriptions">0</span></h1>
            </div>
            <div class="col-7 card-top-right">
              <h3>Total Subscriptions</h3>
            </div>
          </div>
        </div>
        <h4 class="report-card-title">Subscriptions</h4>
        <div class="report-card-bottom">
          <div class="row">
            <div class="col-5">
              <h5>
                <span class="growth-number" id="subscriptions-growth">0</span>
                <span class="fa fa-arrow-up"></span>
              </h5>
            </div>
            <div class="col-7">
              <h5>
                <span class="growth-description">New Subscriptions</span>
              </h5>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="report-card-container col-xl-3 col-lg-6 col-md-6 col-sm-12">
      <div class="report-card-content">
        <div class="report-card-top">
          <div class="row">
            <div class="col-5">
              <h1 id="arrestable-pledges">0</h1>
            </div>
            <div class="col-7 card-top-right">
              <h3>Total Pledges</h3>
            </div>
          </div>
        </div>
        <h4 class="report-card-title">Arrestable Pledges</h4>
        <div class="report-card-bottom">
          <div class="row">
            <div class="col-5">
              <h5>
                <span class="growth-number" id="arrestable-pledges-growth">0</span>
                <span class="fa fa-arrow-up"></span>
              </h5>
            </div>
            <div class="col-7">
              <h5>
                <span class="growth-description">New Pledges</span>
              </h5>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <h5 class="reports-title">Totals Last <span class="filter-day-count">7</span> Days</h5>
  <div class="row">
    <div class="report-card-container col-xl-3 col-lg-6 col-md-6 col-sm-12">
      <div class="report-card-content">
        <div class="report-card-top">
          <div class="row">
            <div class="col-5">
              <h1 id="mobilizations">0</h1>
            </div>
            <div class="col-7 card-top-right">
              <h3>Total Past <span class="filter-day-count">0</span> Days</h3>
            </div>
          </div>
        </div>
        <h4 class="report-card-title">Growth Activities</h4>
        <div class="report-card-bottom">
          <div class="row">
            <div class="col-5">
              <h5>
                <span class="growth-number" id="mobilizations-growth">0</span>
                <span class="fa fa-arrow-up"></span>
              </h5>
            </div>
            <div class="col-7">
              <h5>
              <span class="growth-description">
                Previous
                <span class="filter-day-count">0</span>
                Days
              </span>
              </h5>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="report-card-container col-xl-3 col-lg-6 col-md-6 col-sm-12">
      <div class="report-card-content">
        <div class="report-card-top">
          <div class="row">
            <div class="col-5">
              <h1 id="trainings">0</h1>
            </div>
            <div class="col-7 card-top-right">
              <h3>Total Past <span class="filter-day-count">0</span> Days</h3>
            </div>
          </div>
        </div>
        <h4 class="report-card-title">Trainings</h4>
        <div class="report-card-bottom">
          <div class="row">
            <div class="col-5">
              <h5>
                <span class="growth-number" id="trainings-growth">0</span>
                <span class="fa fa-arrow-up"></span>
              </h5>
            </div>
            <div class="col-7">
              <h5>
              <span class="growth-description">
                Previous
                <span class="filter-day-count">0</span>
                Days
              </span>
              </h5>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="report-card-container col-xl-3 col-lg-6 col-md-6 col-sm-12">
      <div class="report-card-content">
        <div class="report-card-top">
          <div class="row">
            <div class="col-5">
              <h1 id="newsletter-signups">0</h1>
            </div>
            <div class="col-7 card-top-right">
              <h3>Total Past <span class="filter-day-count">0</span> Days</h3>
            </div>
          </div>
        </div>
        <h4 class="report-card-title">Newsletter Signups</h4>
        <div class="report-card-bottom">
          <div class="row">
            <div class="col-5">
              <h5>
                <span class="growth-number" id="newsletter-signups-growth">0</span>
                <span class="fa fa-arrow-up"></span>
              </h5>
            </div>
            <div class="col-7">
              <h5>
              <span class="growth-description">
                Previous
                <span class="filter-day-count">0</span>
                Days
              </span>
              </h5>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="report-card-container col-xl-3 col-lg-6 col-md-6 col-sm-12">
      <div class="report-card-content">
        <div class="report-card-top">
          <div class="row">
            <div class="col-5">
              <h1 id="actions">0</h1>
            </div>
            <div class="col-7 card-top-right">
              <h3>Total Past <span class="filter-day-count">0</span> Days</h3>
            </div>
          </div>
        </div>
        <h4 class="report-card-title">Actions</h4>
        <div class="report-card-bottom">
          <div class="row">
            <div class="col-5">
              <h5>
                <span class="growth-number" id="actions-growth">0</span>
                <span class="fa fa-arrow-up"></span>
              </h5>
            </div>
            <div class="col-7">
              <h5>
              <span class="growth-description">
                Previous
                <span class="filter-day-count">0</span>
                Days
              </span>
              </h5>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/reports/index.html.erb
<div class="content container-fluid">
  <%= render 'report_filter' %>
  <div>
    <%= render 'report_tiles' %>
    <%= render 'report_table' %>
  </div>
  <%= render 'report_charts' %>
</div>